version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp

  webapp:
    build: ./webapp
    expose:
      - "5000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8083:9090"
    depends_on:
      - webapp

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8084:3000"
    depends_on:
      - prometheus

volumes:
  redis-data: